    sudo: required
    dist: trusty
    # language: python
    # python:
    #   - "3.3"
    #   - "3.4"
    #   - "3.5"
    #   - "3.6"

    services:
      - docker
    deploy:
      provider: script
      script: bash docker_push
      on:
        branch: master
        
    # before_install:
    #   - sudo apt-get -y install erlang
    #   - bash install_deps.sh

    # addons:
    # cache:
    #   directories:
    #   - $HOME/artifactory
    # script:
    #   - $HOME/artifactory/artifactory/bin/artifactory.sh &
    #   - sleep 120
